import hashlib
import logging

logger = logging.getLogger(__name__)

ANIMALS = [
    "tigresa",
    "leona",
    "perra",
    "gata",
    "ratona",
    "elefanta",
    "jirafa",
    "mona",
    "osa",
    "loba",
    "liebre",
    "tortuga",
    "buho",
    "aguila",
    "delfin",
    "tiburon",
    "ballena",
    "pulpo",
    "cangreja",
    "cebra",
    "cocodrilo",
    "koala",
    "panda",
    "camella",
    "yegua",
    "oveja",
    "cabra",
    "gallina",
    "bisonte",
    "hipopotama",
    "rinoceronte",
    "leoparda",
    "pantera",
    "gueparda",
    "cierva",
    "alce",
    "ardilla",
    "castora",
    "coneja",
    "hamster",
    "hurona",
    "erizo",
    "topo",
    "murcielago",
    "mapache",
    "nutria",
    "mofeta",
    "comadreja",
    "vaca",
    "mula",
    "gansa",
    "codorniz",
    "paloma",
    "periquita",
    "flamenca",
    "pinguina",
    "pelicana",
    "cigueña",
    "cuervo",
    "gorrion",
    "golondrina",
    "colibri",
    "foca",
    "morsa",
    "orca",
    "manati",
    "medusa",
    "estrella",
    "caballita",
    "langosta",
    "gamba",
    "mejillon",
    "almeja",
    "caracola",
    "babosa",
    "rana",
    "tritona",
    "salamandra",
    "iguana",
    "lagarta",
    "gecko",
    "serpiente",
    "cobra",
    "piton",
    "anaconda",
    "camaleona",
    "avestruz",
    "kiwi",
    "canguro",
    "suricata",
    "llama",
    "alpaca",
    "chimpance",
    "gorila",
    "orangutana",
    "armadillo",
    "hiena",
    "jaguar",
    "puma",
    "antilope",
    "gacela",
    "bufala",
    "jabali",
    "marmota",
    "chinchilla",
    "avispa",
    "abeja",
    "hormiga",
    "mariposa",
    "saltamontes",
    "grillo",
    "escarabajo",
    "mariquita",
    "mantis",
    "luciernaga",
    "polilla",
    "tarantula",
    "escorpiona",
    "catarina",
    "crisalida",
    "grulla",
    "tucana",
    "loro",
    "cuerva",
    "gorriona",
    "albatros",
    "gavina",
    "garza",
    "toca",
    "perdiz",
    "faisana",
    "mirla",
    "ruisenora",
    "corneja",
    "urraca",
    "abubilla",
    "alondra",
    "tordoza",
    "cotorra",
    "lirona",
    "tuza",
    "zarigueya",
    "coati",
    "puercoespin",
    "capibara",
    "tapira",
    "cerda",
    "caballa",
    "trucha",
    "salmon",
    "carpa",
    "anguila",
    "raya",
    "lamprea",
    "esturgeon",
    "mosca",
    "libelula",
]

ADJECTIVES = [
    # Positivas clásicas
    "valiente",
    "fuerte",
    "audaz",
    "fiel",
    "curiosa",
    "traviesa",
    "amigable",
    "generosa",
    "paciente",
    "educada",
    "inteligente",
    "orgullosa",
    "humilde",
    "agradecida",
    "chistosa",
    "feliz",
    "contenta",
    "divertida",
    "simpatica",
    "cariñosa",
    "amable",
    "responsable",
    "relajada",
    "optimista",
    "segura",
    "atrevida",
    "cuidadosa",
    "trabajadora",
    "activa",
    "habladora",
    "silenciosa",
    "dulce",
    "entusiasta",
    "soñadora",
    "ingeniosa",
    "brillante",
    "lista",
    "creativa",
    "imaginativa",
    "observadora",
    "atenta",
    "habil",
    "veloz",
    "agil",
    "ligera",
    "resistente",
    "energica",
    "suave",
    "brava",
    "gentil",
    "noble",
    "leal",
    "bondadosa",
    "mansa",
    "tranquila",
    "alegre",
    "astuta",
    "pequeña",
    "grande",
    "rapida",
    # Galáctica / cósmica
    "galactica",
    "celestial",
    "estelar",
    "cósmica",
    "lunar",
    "solar",
    "sideral",
    "nebulosa",
    "cuantica",
    "orbital",
    "cometa",
    "aurora",
    "astral",
    # Artísticas / creativas
    "artistica",
    "bailaora",
    "cantaora",
    "poetisa",
    "pintora",
    "escultora",
    "cineasta",
    "musica",
    "dramaturga",
    "narradora",
    "fotografa",
    "diseñadora",
    "tejedora",
    "ceramista",
    "ilustradora",
    # Profesiones / roles inspiradores
    "exploradora",
    "inventora",
    "pionera",
    "aventurera",
    "viajera",
    "navegante",
    "alpinista",
    "botanica",
    "geologa",
    "filosofa",
    "matematica",
    "estratega",
    "arquitecta",
    "jardinera",
    "cocinera",
    # Otras positivas y originales
    "luminosa",
    "radiante",
    "vibrante",
    "elegante",
    "encantadora",
    "poderosa",
    "legendaria",
    "mitica",
    "magica",
    "misteriosa",
    "extraordinaria",
    "prodigiosa",
    "deslumbrante",
    "majestuosa",
    "formidable",
    "esplendida",
    "armoniosa",
    "melodiosa",
    "fragante",
    "colorida",
    "vertiginosa",
    "inspiradora",
    "visionaria",
    "apasionada",
    "decidida",
    "perseverante",
    "sabia",
    "intuitiva",
    "empatica",
    "compasiva",
    "solidaria",
    "logopeda",
    "informatica",
    "programadora",
]

assert len(set(ANIMALS)) == len(ANIMALS)
assert len(set(ADJECTIVES)) == len(ADJECTIVES)
assert len(set(ANIMALS + ADJECTIVES)) == len(ANIMALS) + len(ADJECTIVES)

_TOTAL_COMBINATIONS = len(ANIMALS) * len(ADJECTIVES)
_VALID_COMBINATIONS = 200
logger.info(
    "Probabilidad de adivinar una combinación válida al azar: "
    "%d/%d (≈ 1 de cada %.1f intentos, %.4f%%)",
    _VALID_COMBINATIONS,
    _TOTAL_COMBINATIONS,
    _TOTAL_COMBINATIONS / _VALID_COMBINATIONS,
    100 * _VALID_COMBINATIONS / _TOTAL_COMBINATIONS,
)


def generate_valid_combinations(seed: str, num_combinations: int = 200) -> set[str]:
    all_combos = [f"{a}_{adj}" for a in ANIMALS for adj in ADJECTIVES]
    # Hashing determinista para evitar dependencia en random.Random interno de Python
    all_combos.sort(key=lambda c: hashlib.sha256(f"{c}:{seed}".encode()).hexdigest())
    return set(all_combos[:num_combinations])


def normalize_combination(client_id: str) -> str:
    cleaned = client_id.strip().lower()
    cleaned = cleaned.replace(" ", "_").replace("-", "_")
    parts = [p.strip() for p in cleaned.split("_") if p.strip()]
    if len(parts) == 2:
        return f"{parts[0]}_{parts[1]}"
    return cleaned
