import hashlib
import logging

logger = logging.getLogger(__name__)

ANIMALS = [
    "tigre",
    "leon",
    "perro",
    "gato",
    "raton",
    "elefante",
    "jirafa",
    "mono",
    "oso",
    "lobo",
    "zorro",
    "liebre",
    "tortuga",
    "buho",
    "aguila",
    "delfin",
    "tiburon",
    "ballena",
    "pulpo",
    "cangrejo",
    "cebra",
    "cocodrilo",
    "koala",
    "panda",
    "camello",
    "caballo",
    "oveja",
    "cabra",
    "gallina",
    "pato",
    "bisonte",
    "hipopotamo",
    "rinoceronte",
    "leopardo",
    "pantera",
    "guepardo",
    "ciervo",
    "alce",
    "ardilla",
    "castor",
    "conejo",
    "hamster",
    "huron",
    "erizo",
    "topo",
    "murcielago",
    "mapache",
    "nutria",
    "mofeta",
    "comadreja",
    "cerdo",
    "vaca",
    "burro",
    "mula",
    "ganso",
    "pavo",
    "codorniz",
    "paloma",
    "loro",
    "canario",
    "periquito",
    "flamenco",
    "pinguino",
    "pelicano",
    "cigueña",
    "cuervo",
    "gorrion",
    "golondrina",
    "colibri",
    "foca",
    "morsa",
    "orca",
    "manati",
    "medusa",
    "estrella",
    "caballito",
    "langosta",
    "gamba",
    "mejillon",
    "almeja",
    "caracol",
    "babosa",
    "rana",
    "sapo",
    "triton",
    "salamandra",
    "iguana",
    "lagarto",
    "gecko",
    "serpiente",
    "cobra",
    "piton",
    "anaconda",
    "camaleon",
    "avestruz",
    "kiwi",
    "canguro",
    "wombat",
    "tapir",
    "suricata",
    "okapi",
    "yak",
    "llama",
    "alpaca",
    "chimpance",
    "gorila",
    "orangutan",
    "armadillo",
    "hiena",
    "jaguar",
    "puma",
    "antilope",
    "gacela",
    "bufalo",
    "jabali",
    "marmota",
    "chinchilla",
    "avispa",
    "abeja",
    "hormiga",
    "mariposa",
    "libelula",
    "saltamontes",
    "grillo",
    "escarabajo",
    "mariquita",
    "mosca",
    "mosquito",
]

ADJECTIVES = [
    "miedica",
    "valiente",
    "rapido",
    "lento",
    "grande",
    "pequeño",
    "alegre",
    "astuto",
    "torpe",
    "fuerte",
    "debil",
    "manso",
    "feroz",
    "tranquilo",
    "inquieto",
    "timido",
    "audaz",
    "fiel",
    "perezoso",
    "curioso",
    "travieso",
    "amigable",
    "solitario",
    "generoso",
    "paciente",
    "impaciente",
    "educado",
    "limpio",
    "sucio",
    "ordenado",
    "desordenado",
    "inteligente",
    "despistado",
    "orgulloso",
    "humilde",
    "agradecido",
    "chistoso",
    "feliz",
    "contento",
    "enfadado",
    "serio",
    "divertido",
    "simpatico",
    "cariñoso",
    "amable",
    "obediente",
    "rebelde",
    "responsable",
    "nervioso",
    "relajado",
    "optimista",
    "seguro",
    "asustado",
    "atrevido",
    "cuidadoso",
    "descuidado",
    "trabajador",
    "vago",
    "activo",
    "callado",
    "hablador",
    "ruidoso",
    "silencioso",
    "dulce",
    "entusiasta",
    "soñador",
    "realista",
    "ingenioso",
    "brillante",
    "listo",
    "creativo",
    "imaginativo",
    "ingenuo",
    "observador",
    "atento",
    "distraido",
    "habil",
    "torpon",
    "novato",
    "veloz",
    "agil",
    "pesado",
    "ligero",
    "resistente",
    "cansado",
    "energico",
    "fresco",
    "caluroso",
    "frio",
    "suave",
    "duro",
    "blando",
    "rugoso",
    "liso",
    "seco",
    "mojado",
    "caliente",
    "helado",
    "bravo",
    "gentil",
    "noble",
    "leal",
    "bondadoso",
]

assert len(set(ANIMALS)) == len(ANIMALS)
assert len(set(ADJECTIVES)) == len(ADJECTIVES)
assert len(set(ANIMALS + ADJECTIVES)) == len(ANIMALS) + len(ADJECTIVES)


def generate_valid_combinations(seed: str, num_combinations: int = 300) -> set[str]:
    all_combos = [f"{a}_{adj}" for a in ANIMALS for adj in ADJECTIVES]
    # Hashing determinista para evitar dependencia en random.Random interno de Python
    all_combos.sort(key=lambda c: hashlib.sha256(f"{c}:{seed}".encode()).hexdigest())
    return set(all_combos[:num_combinations])


def normalize_combination(client_id: str) -> str:
    cleaned = client_id.strip().lower()
    cleaned = cleaned.replace(" ", "_").replace("-", "_")
    parts = [p.strip() for p in cleaned.split("_") if p.strip()]
    if len(parts) == 2:
        return f"{parts[0]}_{parts[1]}"
    return cleaned
