import hashlib
import logging

logger = logging.getLogger(__name__)

ANIMALS = [
    "tigre",
    "leon",
    "perro",
    "gato",
    "raton",
    "elefante",
    "jirafa",
    "mono",
    "oso",
    "lobo",
    "zorro",
    "liebre",
    "tortuga",
    "buho",
    "aguila",
    "delfin",
    "tiburon",
    "ballena",
    "pulpo",
    "cangrejo",
    "cebra",
    "cocodrilo",
    "koala",
    "panda",
    "camello",
    "caballo",
    "oveja",
    "cabra",
    "gallina",
    "pato",
    "bisonte",
    "hipopotamo",
    "rinoceronte",
    "leopardo",
    "pantera",
    "guepardo",
    "ciervo",
    "alce",
    "ardilla",
    "castor",
    "conejo",
    "hamster",
    "huron",
    "erizo",
    "topo",
    "murcielago",
    "mapache",
    "nutria",
    "mofeta",
    "comadreja",
    "cerdo",
    "vaca",
    "burro",
    "mula",
    "ganso",
    "pavo",
    "codorniz",
    "paloma",
    "loro",
    "canario",
    "periquito",
    "flamenco",
    "pinguino",
    "pelicano",
    "cigueña",
    "cuervo",
    "gorrion",
    "golondrina",
    "colibri",
    "foca",
    "morsa",
    "orca",
    "manati",
    "medusa",
    "estrella",
    "caballito",
    "langosta",
    "gamba",
    "mejillon",
    "almeja",
    "caracol",
    "babosa",
    "rana",
    "sapo",
    "triton",
    "salamandra",
    "iguana",
    "lagarto",
    "gecko",
    "serpiente",
    "cobra",
    "piton",
    "anaconda",
    "camaleon",
    "avestruz",
    "kiwi",
    "canguro",
    "wombat",
    "tapir",
    "suricata",
    "okapi",
    "yak",
    "llama",
    "alpaca",
    "chimpance",
    "gorila",
    "orangutan",
    "armadillo",
    "hiena",
    "jaguar",
    "puma",
    "antilope",
    "gacela",
    "bufalo",
    "jabali",
    "marmota",
    "chinchilla",
    "avispa",
    "abeja",
    "hormiga",
    "mariposa",
    "libelula",
    "saltamontes",
    "grillo",
    "escarabajo",
    "mariquita",
    "mosca",
    "mosquito",
]

ADJECTIVES = [
    "miedica",
    "valiente",
    "rapida",
    "lenta",
    "grande",
    "pequeña",
    "alegre",
    "astuta",
    "torpe",
    "fuerte",
    "debil",
    "mansa",
    "feroz",
    "tranquila",
    "inquieta",
    "timida",
    "audaz",
    "fiel",
    "perezosa",
    "curiosa",
    "traviesa",
    "amigable",
    "solitaria",
    "generosa",
    "paciente",
    "impaciente",
    "educada",
    "limpia",
    "sucia",
    "ordenada",
    "desordenada",
    "inteligente",
    "despistada",
    "orgullosa",
    "humilde",
    "agradecida",
    "chistosa",
    "feliz",
    "contenta",
    "enfadada",
    "seria",
    "divertida",
    "simpatica",
    "cariñosa",
    "amable",
    "obediente",
    "rebelde",
    "responsable",
    "nerviosa",
    "relajada",
    "optimista",
    "segura",
    "asustada",
    "atrevida",
    "cuidadosa",
    "descuidada",
    "trabajadora",
    "vaga",
    "activa",
    "callada",
    "habladora",
    "ruidosa",
    "silenciosa",
    "dulce",
    "entusiasta",
    "soñadora",
    "realista",
    "ingeniosa",
    "brillante",
    "lista",
    "creativa",
    "imaginativa",
    "ingenua",
    "observadora",
    "atenta",
    "distraida",
    "habil",
    "torpona",
    "novata",
    "veloz",
    "agil",
    "pesada",
    "ligera",
    "resistente",
    "cansada",
    "energica",
    "fresca",
    "calurosa",
    "fria",
    "suave",
    "dura",
    "blanda",
    "rugosa",
    "lisa",
    "seca",
    "mojada",
    "caliente",
    "helada",
    "brava",
    "gentil",
    "noble",
    "leal",
    "bondadosa",
]

assert len(set(ANIMALS)) == len(ANIMALS)
assert len(set(ADJECTIVES)) == len(ADJECTIVES)
assert len(set(ANIMALS + ADJECTIVES)) == len(ANIMALS) + len(ADJECTIVES)


def generate_valid_combinations(seed: str, num_combinations: int = 300) -> set[str]:
    all_combos = [f"{a}_{adj}" for a in ANIMALS for adj in ADJECTIVES]
    # Hashing determinista para evitar dependencia en random.Random interno de Python
    all_combos.sort(key=lambda c: hashlib.sha256(f"{c}:{seed}".encode()).hexdigest())
    return set(all_combos[:num_combinations])


def normalize_combination(client_id: str) -> str:
    cleaned = client_id.strip().lower()
    cleaned = cleaned.replace(" ", "_").replace("-", "_")
    parts = [p.strip() for p in cleaned.split("_") if p.strip()]
    if len(parts) == 2:
        return f"{parts[0]}_{parts[1]}"
    return cleaned
